# ==============================
# 🦁 Marketing Beast AI v4.0 PRO (Final Version)
# Built for Fiverr Freelancers & Digital Marketers
# ==============================

import streamlit as st
from groq import Groq
import os
import urllib.parse
import time
from fpdf import FPDF

# -----------------------------
# 📄 PDF GENERATION FUNCTION
# -----------------------------
def create_pdf(ad_copy, image_prompt, product_name, platform):
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(200, 10, txt="MARKETING BEAST AI - REPORT", ln=True, align='C')
    pdf.ln(10)
    
    # Product Info
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(200, 10, txt=f"Product Name: {product_name}", ln=True)
    pdf.cell(200, 10, txt=f"Target Platform: {platform}", ln=True)
    pdf.ln(5)
    
    # Ad Copy Section
    pdf.set_font("Arial", 'B', 14)
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(0, 10, txt="🚀 Generated Ad Copy", ln=True, fill=True)
    pdf.set_font("Arial", size=11)
    pdf.ln(2)
    pdf.multi_cell(0, 8, txt=ad_copy)
    pdf.ln(10)
    
    # Image Prompt Section
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, txt="🎨 AI Visual Strategy (Prompt)", ln=True, fill=True)
    pdf.set_font("Arial", 'I', 11)
    pdf.ln(2)
    pdf.multi_cell(0, 8, txt=image_prompt)
    
    # Footer
    pdf.set_y(-30)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, txt="Generated by Marketing Beast AI - Your Professional Copywriting Partner", align='C')
    
    return pdf.output(dest='S').encode('latin-1', errors='replace')

# -----------------------------
# ⚙️ PAGE CONFIG & CLIENT
# -----------------------------
st.set_page_config(page_title="Marketing Beast AI", page_icon="🦁", layout="wide")

# Load API Key from Secrets
GROQ_API_KEY = st.secrets.get("GROQ_API_KEY") or os.getenv("GROQ_API_KEY")

if not GROQ_API_KEY:
    st.error("❌ API Key Missing! Please add 'GROQ_API_KEY' to Streamlit Secrets.")
    st.stop()

client = Groq(api_key=GROQ_API_KEY)

# Session State for History
if "history" not in st.session_state:
    st.session_state.history = []

# -----------------------------
# 🏰 UI DESIGN
# -----------------------------
st.title("🦁 Marketing Beast AI v4.0 PRO")
st.markdown("### Craft High-Converting Ads & Visual Prompts in Seconds")
st.divider()

col1, col2 = st.columns([1, 1], gap="large")

with col1:
    st.subheader("🎯 Strategy Settings")
    niche = st.text_input("Niche", "E-commerce / Health & Wellness")
    product = st.text_input("Product Name", "The Spiritual Freedom Code")
    platform = st.selectbox("Platform", ["Facebook Ads", "Instagram", "TikTok Ads", "Email Marketing", "Google Ads"])
    tone = st.select_slider("Tone", options=["Minimal", "Inspirational", "Luxury", "Emotional", "Aggressive"])

with col2:
    st.subheader("💡 Product Context")
    pain_point = st.text_area("What is the customer's main pain point?", "Feeling stuck and lost in life")
    benefits = st.text_area("Key Benefits (separate with commas)", "Financial freedom, Inner peace, Abundance")
    affiliate_link = st.text_input("CTA Link (Affiliate/Website)", "https://example.com")

# -----------------------------
# 🔥 CORE LOGIC
# -----------------------------
if st.button("🔥 GENERATE PROFESSIONAL AD STRATEGY"):
    with st.spinner("🧠 AI is analyzing your niche and crafting the beast copy..."):
        
        # Optimized Prompts
        copy_prompt = f"Act as a Senior Copywriter. Write a high-converting {platform} ad for {product} in a {tone} tone. Focus on this pain point: {pain_point}. Benefits: {benefits}. Include a clear CTA: {affiliate_link}. Use hooks and emojis."
        image_prompt_req = f"Create a detailed AI image generation prompt for {product} ad on {platform}. Style: {tone}, cinematic, high resolution, psychological."

        try:
            # Generate Ad Copy
            chat_completion = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[{"role": "user", "content": copy_prompt}],
                temperature=0.7
            )
            ad_copy = chat_completion.choices[0].message.content

            # Generate Image Prompt
            img_completion = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[{"role": "user", "content": image_prompt_req}],
                temperature=0.6
            )
            img_prompt = img_completion.choices[0].message.content

            # Display Results
            st.divider()
            res_col1, res_col2 = st.columns(2)
            
            with res_col1:
                st.success("### 🚀 Professional Ad Copy")
                st.markdown(ad_copy)
                st.code(ad_copy, language="markdown")
            
            with res_col2:
                st.info("### 🎨 AI Image Prompt")
                st.write(img_prompt)
                
                # PDF Download Button
                pdf_data = create_pdf(ad_copy, img_prompt, product, platform)
                st.download_button(
                    label="📥 Download Professional PDF Report",
                    data=pdf_data,
                    file_name=f"Report_{product}.pdf",
                    mime="application/pdf"
                )

            # Save to History
            st.session_state.history.append({"product": product, "copy": ad_copy, "img": img_prompt})

        except Exception as e:
            st.error(f"Error: {str(e)}")

# -----------------------------
# ⏱️ HISTORY SECTION
# -----------------------------
if st.session_state.history:
    st.divider()
    with st.expander("⏱️ View Generation History"):
        for item in reversed(st.session_state.history):
            st.write(f"**Product:** {item['product']}")
            st.caption(f"Prompt: {item['img'][:100]}...")
            st.divider()

st.sidebar.markdown("---")
st.sidebar.info("Built with ❤️ for Fiverr Freelancers")
